version: "3.7"

services:
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./env/mysql.env
    network_mode: host

  spring-boot:
    image: fmarsh/test-database-container
    restart: always
    network_mode: host
    depends_on:
      - mysql
